### ISSUE TITLE
where is define of "linear"

### ISSUE THREAD

**Issue by xauthulei** [houxuedong/makeup-removal#1]
python main.py --phase train --dataset_name facades   --use_labeled_data True
2018-08-20 16:31:07.251953: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2018-08-20 16:31:07.251975: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2018-08-20 16:31:07.251981: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2018-08-20 16:31:07.251986: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2018-08-20 16:31:07.251991: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Traceback (most recent call last):
  File "main.py", line 73, in <module>
    tf.app.run()
  File "/anaconda3/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 65, in main
    n_critic = args.n_critic, use_labeled_data = args.use_labeled_data, clamp = args.clamp)
  File "/Users/llhu/AIDemo/demo/model3.py", line 63, in __init__
    self.build_model()
  File "/Users/llhu/AIDemo/demo/model3.py", line 95, in build_model
    self.predictions_PAB_pair = self.C_d_net(tf.concat( [self.real_PA,self.real_PB],3), reuse = False)
  File "/Users/llhu/AIDemo/demo/model3.py", line 442, in C_d_net
    return self.discriminator(imgs, prefix = 'C_', reuse = reuse)
  File "/Users/llhu/AIDemo/demo/model3.py", line 431, in discriminator
    h4 = linear(tf.reshape(h3, [self.batch_size, -1]), 1, prefix+'d_h3_lin')
NameError: name 'linear' is not defined

**Comment by xauthulei** [comment]
Could offered a demo for this, I can't run well
===================================
 python main.py --phase train --dataset_name facades   --use_labeled_data False
2018-08-20 16:52:22.287901: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2018-08-20 16:52:22.287922: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2018-08-20 16:52:22.287928: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2018-08-20 16:52:22.287933: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2018-08-20 16:52:22.287937: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
101.0
True
 [*] Reading checkpoint...
 [!] Load failed...
0
0
0
0
0
0
0
0
0
0
0
0
......
